export function createEditorActionRegistry({
  boardCodeActions,
  boardMetaControls,
  editorContext,
  historyControls,
  inspectorControls,
  localBoardsPanel,
  objectCommands,
  viewportControls,
}) {
  return {
    applyFitZoom: viewportControls.applyFitZoom,
    applyFitZoomOnResize: viewportControls.applyFitZoomOnResize,
    centerSelected: objectCommands.centerSelected,
    clearBoard: objectCommands.clearBoard,
    copySelected: objectCommands.copySelected,
    deleteLocalBoard: localBoardsPanel.deleteLocalBoard,
    deleteSelected: objectCommands.deleteSelected,
    deselect: editorContext.deselect,
    duplicateSelected: objectCommands.duplicateSelected,
    exportCode: boardCodeActions.exportCode,
    loadFromCode: boardCodeActions.loadFromCode,
    loadLocalBoard: localBoardsPanel.loadLocalBoard,
    moveSelected: objectCommands.moveSelected,
    nudgeSelected: objectCommands.nudgeSelected,
    onBackgroundChange: boardMetaControls.onBackgroundChange,
    onBoardNameChange: boardMetaControls.onBoardNameChange,
    pasteObject: objectCommands.pasteObject,
    redo: historyControls.redo,
    renderPreview: boardCodeActions.renderPreview,
    saveLocalBoard: localBoardsPanel.saveLocalBoard,
    setStageZoom: viewportControls.setStageZoom,
    stepZoom: viewportControls.stepZoom,
    toggleGrid: viewportControls.toggleGrid,
    toggleSnapToGrid: viewportControls.toggleSnapToGrid,
    undo: historyControls.undo,
    updateLocalBoardButtons: localBoardsPanel.updateLocalBoardButtons,
    updateSelectedFromInspector: inspectorControls.updateSelectedFromInspector,
  }
}
