export function createEditorActionRegistry({
  boardCodeActions,
  boardMetaControls,
  editorContext,
  historyControls,
  inspectorControls,
  localBoardsPanel,
  objectCommands,
  projectFileActions,
  viewportControls,
}) {
  return {
    applyFitZoom: viewportControls.applyFitZoom,
    applyFitZoomOnResize: viewportControls.applyFitZoomOnResize,
    addObjectAt: objectCommands.addObjectAt,
    alignSelected: objectCommands.alignSelected,
    centerSelected: objectCommands.centerSelected,
    clearBoard: objectCommands.clearBoard,
    copySelected: objectCommands.copySelected,
    copyExportCode: boardCodeActions.copyExportCode,
    copyExportImage: boardCodeActions.copyExportImage,
    deleteLocalBoard: localBoardsPanel.deleteLocalBoard,
    deleteSelectedLocalBoards: localBoardsPanel.deleteSelectedLocalBoards,
    deleteSelected: objectCommands.deleteSelected,
    deselect: editorContext.deselect,
    duplicateSelected: objectCommands.duplicateSelected,
    downloadPreviewImage: boardCodeActions.downloadPreviewImage,
    downloadProjectFile: projectFileActions.downloadProjectFile,
    exportCode: boardCodeActions.exportCode,
    importProjectFile: projectFileActions.importProjectFile,
    loadFromCode: boardCodeActions.loadFromCode,
    loadLocalBoard: localBoardsPanel.loadLocalBoard,
    newLocalBoard: localBoardsPanel.newLocalBoard,
    getLastLayerIndex: objectCommands.getLastLayerIndex,
    groupSelected: objectCommands.groupSelected,
    ungroupSelectedGroup: objectCommands.ungroupSelectedGroup,
    toggleLayerGroup: objectCommands.toggleLayerGroup,
    toggleLayerGroupFlag: objectCommands.toggleLayerGroupFlag,
    renameLayerGroup: objectCommands.renameLayerGroup,
    moveSelected: objectCommands.moveSelected,
    moveSelectedTo: objectCommands.moveSelectedTo,
    nudgeSelected: objectCommands.nudgeSelected,
    onBackgroundChange: boardMetaControls.onBackgroundChange,
    onBoardNameChange: boardMetaControls.onBoardNameChange,
    pasteObject: objectCommands.pasteObject,
    redo: historyControls.redo,
    renderLocalBoards: localBoardsPanel.renderLocalBoards,
    renderPreview: boardCodeActions.renderPreview,
    saveLocalBoard: localBoardsPanel.saveLocalBoard,
    saveLocalBoardAs: localBoardsPanel.saveLocalBoardAs,
    selectObject: editorContext.selectObject,
    setMarqueeSelectionMode: editorContext.setMarqueeSelectionMode,
    setStageZoom: viewportControls.setStageZoom,
    stepZoom: viewportControls.stepZoom,
    toggleGrid: viewportControls.toggleGrid,
    toggleLayerFlagForSelection: objectCommands.toggleSelectedLayerFlag,
    toggleSnapToGrid: viewportControls.toggleSnapToGrid,
    undo: historyControls.undo,
    updateLocalBoardButtons: localBoardsPanel.updateLocalBoardButtons,
    updateSelectedFromInspector: inspectorControls.updateSelectedFromInspector,
  }
}
