/**
 * Object names shown in the editor's Simplified Chinese UI.
 *
 * Keep these keys aligned with the internal object types. Values are UI-only
 * and must never be written to Board, Project, or share-code data.
 */
export const OBJECT_NAMES_ZH_CN = {
  // 职业/特职（按内部类型顺序，对应游戏列表 48 → 1）
  tank: '防护职业',
  tank_1: '防护职业1',
  tank_2: '防护职业2',
  healer: '治疗职业',
  healer_1: '治疗职业1',
  healer_2: '治疗职业2',
  pure_healer: '纯粹治疗职业',
  barrier_healer: '护罩治疗职业',
  dps: '进攻职业',
  dps_1: '进攻职业1',
  dps_2: '进攻职业2',
  dps_3: '进攻职业3',
  dps_4: '进攻职业4',
  melee_dps: '近战职业',
  ranged_dps: '远程职业',
  physical_ranged_dps: '远程物理职业',
  magical_ranged_dps: '远程魔法职业',
  paladin: '骑士',
  warrior: '战士',
  dark_knight: '暗黑骑士',
  gunbreaker: '绝枪战士',
  white_mage: '白魔法师',
  scholar: '学者',
  astrologian: '占星术士',
  sage: '贤者',
  monk: '武僧',
  dragoon: '龙骑士',
  ninja: '忍者',
  samurai: '武士',
  reaper: '钐镰客',
  viper: '蝰蛇剑士',
  bard: '吟游诗人',
  machinist: '机工士',
  dancer: '舞者',
  black_mage: '黑魔法师',
  summoner: '召唤师',
  red_mage: '赤魔法师',
  pictomancer: '绘灵法师',
  blue_mage: '青魔法师',
  gladiator: '剑术师',
  marauder: '斧术师',
  conjurer: '幻术师',
  pugilist: '格斗家',
  lancer: '枪术师',
  rogue: '双剑师',
  archer: '弓箭手',
  thaumaturge: '咒术师',
  arcanist: '秘术师',

  // 机制
  gaze: '视线判定',
  stack: '分摊',
  line_stack: '直线分摊',
  proximity: '距离衰减',
  stack_multi: '连续分摊',
  proximity_player: '玩家距离衰减',
  tankbuster: '坦克死刑',
  radial_knockback: '圆形击退',
  linear_knockback: '直线击退',
  tower: '塔',
  targeting: '点名',
  moving_circle_aoe: '移动圆形范围',
  '1person_aoe': '1 人范围',
  '2person_aoe': '2 人范围',
  '3person_aoe': '3 人范围',
  '4person_aoe': '4 人范围',

  // 标记
  small_enemy: '小型敌人',
  medium_enemy: '中型敌人',
  large_enemy: '大型敌人',
  enhancement: '强化效果',
  enfeeblement: '弱化效果',
  attack_1: '攻击标记 1',
  attack_2: '攻击标记 2',
  attack_3: '攻击标记 3',
  attack_4: '攻击标记 4',
  attack_5: '攻击标记 5',
  attack_6: '攻击标记 6',
  attack_7: '攻击标记 7',
  attack_8: '攻击标记 8',
  bind_1: '止步标记 1',
  bind_2: '止步标记 2',
  bind_3: '止步标记 3',
  ignore_1: '无视标记 1',
  ignore_2: '无视标记 2',
  square_marker: '方块标记',
  circle_marker: '圆圈标记',
  plus_marker: '十字标记',
  triangle_marker: '三角标记',
  waymark_a: '场地标记 A',
  waymark_b: '场地标记 B',
  waymark_c: '场地标记 C',
  waymark_d: '场地标记 D',
  waymark_1: '场地标记 1',
  waymark_2: '场地标记 2',
  waymark_3: '场地标记 3',
  waymark_4: '场地标记 4',
  lockon_red: '红色锁定标记',
  lockon_blue: '蓝色锁定标记',
  lockon_purple: '紫色锁定标记',
  lockon_green: '绿色锁定标记',

  // 形状
  shape_circle: '圆形符号',
  shape_x: '叉形符号',
  shape_triangle: '三角符号',
  shape_square: '方形符号',
  up_arrow: '向上箭头',
  rotate: '旋转符号',
  highlighted_circle: '高亮圆形符号',
  highlighted_x: '高亮叉形符号',
  highlighted_square: '高亮方形符号',
  highlighted_triangle: '高亮三角符号',
  rotate_clockwise: '顺时针旋转',
  rotate_counterclockwise: '逆时针旋转',

  // 地面
  checkered_circle: '棋盘格圆形区域',
  checkered_square: '棋盘格方形区域',
  grey_circle: '灰色圆形区域',
  grey_square: '灰色方形区域',

  // 编辑器内建对象
  text: '文本',
  line: '直线',
  line_aoe: '直线范围',
  circle_aoe: '圆形范围',
  fan_aoe: '扇形范围',
  donut: '环形范围',
} as const

export type ObjectNameKey = keyof typeof OBJECT_NAMES_ZH_CN
