/**
 * Object names shown in the editor's Simplified Chinese UI.
 *
 * Keep these keys aligned with the internal object types. Values are UI-only
 * and must never be written to Board, Project, or share-code data.
 */
export const OBJECT_NAMES_ZH_CN = {
  // 职业/特职（按内部类型顺序，对应游戏列表 48 → 1）
  tank: '防护职业',
  tank_1: '防护职业1',
  tank_2: '防护职业2',
  healer: '治疗职业',
  healer_1: '治疗职业1',
  healer_2: '治疗职业2',
  pure_healer: '纯粹治疗职业',
  barrier_healer: '护罩治疗职业',
  dps: '进攻职业',
  dps_1: '进攻职业1',
  dps_2: '进攻职业2',
  dps_3: '进攻职业3',
  dps_4: '进攻职业4',
  melee_dps: '近战职业',
  ranged_dps: '远程职业',
  physical_ranged_dps: '远程物理职业',
  magical_ranged_dps: '远程魔法职业',
  paladin: '骑士',
  warrior: '战士',
  dark_knight: '暗黑骑士',
  gunbreaker: '绝枪战士',
  white_mage: '白魔法师',
  scholar: '学者',
  astrologian: '占星术士',
  sage: '贤者',
  monk: '武僧',
  dragoon: '龙骑士',
  ninja: '忍者',
  samurai: '武士',
  reaper: '钐镰客',
  viper: '蝰蛇剑士',
  bard: '吟游诗人',
  machinist: '机工士',
  dancer: '舞者',
  black_mage: '黑魔法师',
  summoner: '召唤师',
  red_mage: '赤魔法师',
  pictomancer: '绘灵法师',
  blue_mage: '青魔法师',
  gladiator: '剑术师',
  marauder: '斧术师',
  conjurer: '幻术师',
  pugilist: '格斗家',
  lancer: '枪术师',
  rogue: '双剑师',
  archer: '弓箭手',
  thaumaturge: '咒术师',
  arcanist: '秘术师',

  // 攻击范围（图标部分按内部类型顺序，对应游戏列表 17 → 1）
  gaze: '视线攻击',
  stack: '分摊伤害攻击',
  line_stack: '分摊伤害攻击：直线型',
  proximity: '距离衰减攻击',
  stack_multi: '分摊伤害攻击：连续型',
  proximity_player: '距离衰减攻击：特定对象型',
  tankbuster: '强攻击',
  radial_knockback: '击退攻击：放射型',
  linear_knockback: '击退攻击：直线型',
  tower: '踩塔机制',
  targeting: '针对目标的预兆',
  moving_circle_aoe: '圆形范围攻击：移动型',
  '1person_aoe': '1人用区域',
  '2person_aoe': '2人用区域',
  '3person_aoe': '3人用区域',
  '4person_aoe': '4人用区域',

  // 图标/标记（按内部类型顺序，对应游戏列表 34 → 1）
  small_enemy: '小型敌人',
  medium_enemy: '中型敌人',
  large_enemy: '大型敌人',
  enhancement: '强化状态',
  enfeeblement: '弱化状态',
  attack_1: '攻击1',
  attack_2: '攻击2',
  attack_3: '攻击3',
  attack_4: '攻击4',
  attack_5: '攻击5',
  attack_6: '攻击6',
  attack_7: '攻击7',
  attack_8: '攻击8',
  bind_1: '止步1',
  bind_2: '止步2',
  bind_3: '止步3',
  ignore_1: '禁止1',
  ignore_2: '禁止2',
  square_marker: '方块',
  circle_marker: '圆圈',
  plus_marker: '十字',
  triangle_marker: '三角',
  waymark_a: '场景标记A',
  waymark_b: '场景标记B',
  waymark_c: '场景标记C',
  waymark_d: '场景标记D',
  waymark_1: '场景标记1',
  waymark_2: '场景标记2',
  waymark_3: '场景标记3',
  waymark_4: '场景标记4',
  lockon_red: '瞄准标记（红色）',
  lockon_blue: '瞄准标记（蓝色）',
  lockon_purple: '瞄准标记（紫色）',
  lockon_green: '瞄准标记（绿色）',

  // 图形/记号（图标部分按内部类型顺序，对应游戏列表 13 → 2）
  shape_circle: '圆圈',
  shape_x: '叉',
  shape_triangle: '三角',
  shape_square: '方块',
  up_arrow: '箭头',
  rotate: '旋转',
  highlighted_circle: '高光圆圈',
  highlighted_x: '高光叉',
  highlighted_square: '高光方块',
  highlighted_triangle: '高光三角',
  rotate_clockwise: '顺时针旋转',
  rotate_counterclockwise: '逆时针旋转',

  // 场地（按内部类型顺序，对应游戏列表 4 → 1）
  checkered_circle: '圆形格子底',
  checkered_square: '正方形格子底',
  grey_circle: '圆形灰底',
  grey_square: '正方形灰底',

  // 编辑器内建对象
  text: '文字',
  line: '线',
  line_aoe: '直线范围攻击',
  circle_aoe: '圆形范围攻击',
  fan_aoe: '扇形范围攻击',
  donut: '环形范围攻击',
} as const

export type ObjectNameKey = keyof typeof OBJECT_NAMES_ZH_CN

/**
 * Optional search aliases for the Simplified Chinese UI.
 *
 * Names are always searchable and do not need to be repeated here. Add any
 * number of aliases to an object's array; aliases are UI-only metadata.
 */
export const OBJECT_ALIASES_ZH_CN = {
  // 职业/特职
  tank: ['坦克', 'T'],
  tank_1: ['坦克1', 'T1'],
  tank_2: ['坦克2', 'T2'],
  healer: ['治疗', '奶妈', 'H'],
  healer_1: ['治疗1', 'H1'],
  healer_2: ['治疗2', 'H2'],
  pure_healer: ['纯奶', '纯治疗'],
  barrier_healer: ['盾奶'],
  dps: ['输出', 'DPS'],
  dps_1: ['输出1', 'D1'],
  dps_2: ['输出2', 'D2'],
  dps_3: ['输出3', 'D3'],
  dps_4: ['输出4', 'D4'],
  melee_dps: ['近战 DPS'],
  ranged_dps: ['远程 DPS'],
  physical_ranged_dps: ['远敏', '物理远程'],
  magical_ranged_dps: ['法系', '魔法远程'],
  paladin: ['剑骑', 'PLD'],
  warrior: ['战坦', 'WAR'],
  dark_knight: ['黑骑', 'DK', 'DRK'],
  gunbreaker: ['绝枪', '枪刃', 'GNB'],
  white_mage: ['白魔', 'WHM'],
  scholar: ['SCH'],
  astrologian: ['占星', 'AST'],
  sage: ['SGE'],
  monk: ['MNK'],
  dragoon: ['龙骑', 'DRG'],
  ninja: ['NIN'],
  samurai: ['SAM'],
  reaper: ['镰刀', 'RPR'],
  viper: ['蝰蛇', 'VPR'],
  bard: ['诗人', 'BRD'],
  machinist: ['机工', 'MCH'],
  dancer: ['DNC'],
  black_mage: ['黑魔', 'BLM'],
  summoner: ['召唤', 'SMN'],
  red_mage: ['赤魔', 'RDM'],
  pictomancer: ['绘灵', '画家', 'PCT'],
  blue_mage: ['青魔', 'BLU'],
  gladiator: ['剑术'],
  marauder: ['斧术'],
  conjurer: ['幻术'],
  pugilist: ['格斗'],
  lancer: ['枪术'],
  rogue: ['双剑'],
  archer: ['弓术'],
  thaumaturge: ['咒术'],
  arcanist: ['秘术'],

  // 攻击范围
  gaze: ['背对', '视线'],
  stack: ['集合', '分伤'],
  line_stack: ['直线分伤'],
  proximity: ['远离', '衰减'],
  stack_multi: ['多次分摊'],
  proximity_player: ['点名衰减', '远离玩家'],
  tankbuster: ['死刑', '坦克强攻'],
  radial_knockback: ['中心击退', '放射击退'],
  linear_knockback: ['方向击退'],
  tower: [],
  targeting: ['锁定目标'],
  moving_circle_aoe: ['移动 AOE', '追踪范围'],
  '1person_aoe': ['单人区域', '单人 AOE'],
  '2person_aoe': ['双人区域', '双人 AOE'],
  '3person_aoe': ['三人区域', '三人 AOE'],
  '4person_aoe': ['四人区域', '四人 AOE'],

  // 图标/标记
  small_enemy: ['小怪', '敌人'],
  medium_enemy: ['中怪', '敌人'],
  large_enemy: ['大怪', '首领', 'BOSS'],
  enhancement: ['增益', 'BUFF'],
  enfeeblement: ['减益', 'DEBUFF'],
  attack_1: [],
  attack_2: [],
  attack_3: [],
  attack_4: [],
  attack_5: [],
  attack_6: [],
  attack_7: [],
  attack_8: [],
  bind_1: [],
  bind_2: [],
  bind_3: [],
  ignore_1: [],
  ignore_2: [],
  square_marker: [],
  circle_marker: [],
  plus_marker: ['加号'],
  triangle_marker: [],
  waymark_a: ['标点A', '地标A'],
  waymark_b: ['标点B', '地标B'],
  waymark_c: ['标点C', '地标C'],
  waymark_d: ['标点D', '地标D'],
  waymark_1: ['标点1', '地标1'],
  waymark_2: ['标点2', '地标2'],
  waymark_3: ['标点3', '地标3'],
  waymark_4: ['标点4', '地标4'],
  lockon_red: ['红色点名', '红锁'],
  lockon_blue: ['蓝色点名', '蓝锁'],
  lockon_purple: ['紫色点名', '紫锁'],
  lockon_green: ['绿色点名', '绿锁'],

  // 图形/记号
  shape_circle: [],
  shape_x: ['叉号', 'X形'],
  shape_triangle: [],
  shape_square: [],
  up_arrow: ['上箭头'],
  rotate: ['循环'],
  highlighted_circle: [],
  highlighted_x: [],
  highlighted_square: [],
  highlighted_triangle: [],
  rotate_clockwise: ['右旋'],
  rotate_counterclockwise: ['左旋'],

  // 场地
  checkered_circle: ['棋盘格', '圆形地面'],
  checkered_square: ['棋盘格', '方形地面'],
  grey_circle: ['灰色地面', '圆形地面'],
  grey_square: ['灰色地面', '方形地面'],

  // 编辑器内建对象
  text: ['标签'],
  line: ['线段', '连线'],
  line_aoe: ['矩形范围', '直线 AOE'],
  circle_aoe: ['圆形 AOE', '圆圈范围'],
  fan_aoe: ['扇形 AOE', '扇区'],
  donut: ['月环', '甜甜圈', '环形 AOE'],
} satisfies Record<ObjectNameKey, readonly string[]>
