import assert from 'node:assert/strict'
import test from 'node:test'

import { createEditorActionRegistry } from '../../src/web/editorActionRegistry.js'
import type { EditorActionRegistry } from '../../src/web/types.js'

type ActionHandlers = {
  [Key in keyof EditorActionRegistry]: EditorActionRegistry[Key]
}

test('createEditorActionRegistry exposes the event binding action surface', () => {
  const actionNames = [
    'applyFitZoom',
    'applyFitZoomOnResize',
    'addObjectAt',
    'alignSelected',
    'clearBoard',
    'copyExportCode',
    'copyExportImage',
    'copySelected',
    'deletePreset',
    'deleteLocalBoard',
    'deleteSelectedLocalBoards',
    'deleteSelected',
    'deselect',
    'downloadPreviewImage',
    'downloadProjectFile',
    'duplicateSelected',
    'exportCode',
    'importProjectFile',
    'insertPresetAt',
    'getLastLayerIndex',
    'groupSelected',
    'moveLayerNodeAfter',
    'moveLayerNodeBefore',
    'moveLayerNodeIntoGroup',
    'moveLayerNodeToRoot',
    'ungroupSelectedGroup',
    'toggleLayerGroup',
    'toggleLayerGroupFlag',
    'renameLayerGroup',
    'loadFromCode',
    'loadLocalBoard',
    'moveSelected',
    'moveSelectedTo',
    'newLocalBoard',
    'nudgeSelected',
    'onBackgroundChange',
    'onBoardNameChange',
    'onFileNameInput',
    'pasteObject',
    'redo',
    'renderLocalBoards',
    'renderLocalPresets',
    'renderPreview',
    'saveLocalBoard',
    'saveLocalBoardAs',
    'saveSelectedPreset',
    'selectLayerGroup',
    'selectObject',
    'setGridDensity',
    'setGridOpacity',
    'setStageZoom',
    'stepZoom',
    'toggleGrid',
    'toggleLayerFlagForSelection',
    'toggleSnapToGrid',
    'undo',
    'updateLocalBoardButtons',
    'updatePresetButtons',
    'updateSelectedFromInspector',
  ] as const satisfies readonly (keyof EditorActionRegistry)[]
  const handlers = Object.fromEntries(
    actionNames.map((name) => [name, () => name]),
  ) as unknown as ActionHandlers

  const actions = createEditorActionRegistry({
    boardCodeActions: {
      copyExportCode: handlers.copyExportCode,
      copyExportImage: handlers.copyExportImage,
      downloadPreviewImage: handlers.downloadPreviewImage,
      exportCode: handlers.exportCode,
      loadFromCode: handlers.loadFromCode,
      renderPreview: handlers.renderPreview,
    },
    boardMetaControls: {
      onBackgroundChange: handlers.onBackgroundChange,
      onBoardNameChange: handlers.onBoardNameChange,
      renderBackgroundOptions: () => {},
      syncBoardNameInput: () => {},
    },
    editorContext: {
      deselect: handlers.deselect,
      getSelected: () => undefined,
      getSelectedList: () => [],
      getSnapStep: () => 0,
      normalizeCoordinate: (value: number) => value,
      normalizePoint: (x: number, y: number) => ({ x, y }),
      selectLayerGroup: handlers.selectLayerGroup,
      selectObject: handlers.selectObject,
      selectObjects: () => {},
    },
    historyControls: {
      redo: handlers.redo,
      undo: handlers.undo,
    },
    inspectorControls: {
      renderInspector: () => {},
      updateSelectedFromInspector: handlers.updateSelectedFromInspector,
      updateSelectionActions: () => {},
    },
    localBoardsPanel: {
      confirmDocumentReplacement: async () => true,
      deleteLocalBoard: handlers.deleteLocalBoard,
      deleteSelectedLocalBoards: handlers.deleteSelectedLocalBoards,
      loadLocalBoard: handlers.loadLocalBoard,
      newLocalBoard: handlers.newLocalBoard,
      onFileNameInput: handlers.onFileNameInput,
      renameLocalBoard: async () => true,
      renderLocalBoards: handlers.renderLocalBoards,
      saveLocalBoard: handlers.saveLocalBoard,
      saveLocalBoardAs: handlers.saveLocalBoardAs,
      updateLocalBoardButtons: handlers.updateLocalBoardButtons,
    },
    localPresetsPanel: {
      deletePreset: handlers.deletePreset,
      insertPresetAt: handlers.insertPresetAt,
      renderLocalPresets: handlers.renderLocalPresets,
      saveSelectedPreset: handlers.saveSelectedPreset,
      updatePresetButtons: handlers.updatePresetButtons,
    },
    objectCommands: {
      addObject: () => {},
      alignSelected: handlers.alignSelected,
      clearBoard: handlers.clearBoard,
      copySelected: handlers.copySelected,
      deleteSelected: handlers.deleteSelected,
      duplicateSelected: handlers.duplicateSelected,
      addObjectAt: handlers.addObjectAt,
      getLastLayerIndex: handlers.getLastLayerIndex,
      groupSelected: handlers.groupSelected,
      moveLayerNodeAfter: handlers.moveLayerNodeAfter,
      moveLayerNodeBefore: handlers.moveLayerNodeBefore,
      moveLayerNodeIntoGroup: handlers.moveLayerNodeIntoGroup,
      moveLayerNodeToRoot: handlers.moveLayerNodeToRoot,
      ungroupSelectedGroup: handlers.ungroupSelectedGroup,
      toggleLayerGroup: handlers.toggleLayerGroup,
      toggleLayerGroupFlag: handlers.toggleLayerGroupFlag,
      renameLayerGroup: handlers.renameLayerGroup,
      moveSelected: handlers.moveSelected,
      moveSelectedTo: handlers.moveSelectedTo,
      nudgeSelected: handlers.nudgeSelected,
      pasteObject: handlers.pasteObject,
      reorderLayer: () => {},
      toggleLayerFlag: () => {},
      toggleSelectedLayerFlag: handlers.toggleLayerFlagForSelection,
    },
    projectFileActions: {
      downloadProjectFile: handlers.downloadProjectFile,
      importProjectFile: handlers.importProjectFile,
    },
    viewportControls: {
      applyFitZoom: handlers.applyFitZoom,
      applyFitZoomOnResize: handlers.applyFitZoomOnResize,
      applyInitialZoom: () => {},
      setGridDensity: handlers.setGridDensity,
      setGridOpacity: handlers.setGridOpacity,
      setStageZoom: handlers.setStageZoom,
      stepZoom: handlers.stepZoom,
      toggleGrid: handlers.toggleGrid,
      toggleSnapToGrid: handlers.toggleSnapToGrid,
      syncControlStateFromDom: () => {},
    },
  })

  assert.deepEqual(Object.keys(actions).sort(), Object.keys(handlers).sort())
  for (const name of actionNames) {
    const handler = handlers[name]
    assert.equal(actions[name], handler)
  }
})
